mqtt:
    host: 192.168.0.133
    port: 1883
    client: kamstrup
    topic: kamstrup
    qos: 0
    retain: False
    authentication: True
    username: mosquito
    password: mosquito
serial_device:
    com_port: /dev/ttyUSB1
kamstrup:
    parameters:
    - energy
    - volume
    - temp1
    - temp2
    poll_interval: 180
